---
kind: pipeline
type: docker
name: build-and-push-develop

steps:

  - name: docker build an publish
    image: docker.struchkov.dev/docker-buildx:latest
    environment:
      DOCKER_REGISTRY_TOKEN:
        from_secret: DOCKER_REGISTRY_TOKEN
      DOCKER_REGISTRY_USER:
        from_secret: DOCKER_REGISTRY_USER
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 15
      - echo "$DOCKER_REGISTRY_TOKEN" | docker login docker.struchkov.dev --username $DOCKER_REGISTRY_USER --password-stdin
      - echo "$DOCKER_REGISTRY_TOKEN" | docker login hub.docker.struchkov.dev --username $DOCKER_REGISTRY_USER --password-stdin
      - docker buildx create --use
      - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t "docker.struchkov.dev/samba:develop" .

trigger:
  branch:
    - develop

services:
  - name: docker
    image: hub.docker.struchkov.dev/docker:24.0.7-dind-alpine3.18
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

image_pull_secrets:
  - DOCKER_AUTH
---
kind: pipeline
type: docker
name: build-and-push-release

steps:

  - name: docker build an publish
    image: docker.struchkov.dev/docker-buildx:latest
    environment:
      DOCKER_REGISTRY_TOKEN:
        from_secret: DOCKER_REGISTRY_TOKEN
      DOCKER_REGISTRY_USER:
        from_secret: DOCKER_REGISTRY_USER
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 15
      - echo "$DOCKER_REGISTRY_TOKEN" | docker login docker.struchkov.dev --username $DOCKER_REGISTRY_USER --password-stdin
      - echo "$DOCKER_REGISTRY_TOKEN" | docker login hub.docker.struchkov.dev --username $DOCKER_REGISTRY_USER --password-stdin
      - docker buildx create --use
      - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t "docker.struchkov.dev/samba:latest" -t "docker.struchkov.dev/samba:$DRONE_TAG" .

trigger:
  ref:
    - refs/tags/*

services:
  - name: docker
    image: hub.docker.struchkov.dev/docker:24.0.7-dind-alpine3.18
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

image_pull_secrets:
  - DOCKER_AUTH
---
kind: signature
hmac: bf70dbc39853ab693c0a6c788975244211a0dbdf8b83a8447ca53cdf5ba39b29

...
